### ISSUE TITLE
what pages to convert

### ISSUE THREAD

**Issue by wsor4035** [wsor4035/devwiki#1]
* [x] https://dev.minetest.net/All_rules_regarding_to_development
* [x] https://dev.minetest.net/Changelog
* [x] https://dev.minetest.net/Code_style_guidelines
* [x] https://dev.minetest.net/Development_Tools
* [x] https://dev.minetest.net/Development_troubleshooting
* [x] https://dev.minetest.net/Engine
* [x] https://dev.minetest.net/Engine/Basic_data_structures
* [x] https://dev.minetest.net/Engine/NMPR
* [x] https://dev.minetest.net/Engine/Network_Protocol
* [x] https://dev.minetest.net/Engine/Objects
* [x] https://dev.minetest.net/Engine/Script_Engine
* [x] https://dev.minetest.net/Engine/Structure
* [x] https://dev.minetest.net/Git_Guidelines
* [x] https://dev.minetest.net/Introduction_to_L-system_trees
* [x] https://dev.minetest.net/L-system_tree_examples
* [x] https://dev.minetest.net/List_of_hardcoded_features
* [x] https://dev.minetest.net/Lua_Optimization_Tips
* [x] https://dev.minetest.net/Lua_code_style_guidelines
* [x] https://dev.minetest.net/Main_Page
* [x] https://dev.minetest.net/Mapgen_Parameters
* [x] https://dev.minetest.net/Mapgen_memory_optimisations
* [x] https://dev.minetest.net/Meetings
* [x] https://dev.minetest.net/Merging_core_pull_requests_to_upstream
* [x] https://dev.minetest.net/Minetest_Schematic_File_Format
* [x] https://dev.minetest.net/Mod_interoperability
* [x] https://dev.minetest.net/Modding_Intro
* [x] https://dev.minetest.net/Modding_Tips
* [x] https://dev.minetest.net/OldChangelog
* [x] https://dev.minetest.net/Organisation
* [x] https://dev.minetest.net/Player-World_Interaction
* [x] https://dev.minetest.net/Player_physics
* [x] https://dev.minetest.net/Profiler_graph
* [x] https://dev.minetest.net/Releasing_Luanti
* [x] https://dev.minetest.net/Spawn_Algorithm
* [x] https://dev.minetest.net/SteamDeck
* [x] https://dev.minetest.net/Translating_a_game_on_Weblate
* [x] https://dev.minetest.net/Translation
* [x] https://dev.minetest.net/Translation/Mods_and_Games
* [x] https://dev.minetest.net/schematic

see https://dev.minetest.net/index.php?title=Special:AllPages&hideredirects=1 - worthless pages are ignored

**Comment by rollerozxa** [comment]
These pages probably won't need to be converted:
- https://dev.minetest.net/Android_code_style_guidelines: Stub, not much of use
- https://dev.minetest.net/Engine/Mapgen: the code is so obsolete it's worse than useless for making a custom C++ mapgen
- Proposals/*: seems to be some kind of old attempt at RFCs, don't think they should be brought over
- https://dev.minetest.net/Minetest_Game_development: obsolete

**Comment by wsor4035** [comment]
gone, thanks

**Comment by wsor4035** [comment]
burning https://dev.minetest.net/Compiling_Luanti, https://dev.minetest.net/Git, and https://dev.minetest.net/How_to_start_contributing per zughy suggestion

**Comment by wsor4035** [comment]
completed
